# Generated by Django 5.2.5 on 2025-08-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LayananGrooming',
            fields=[
                ('id_grooming', models.AutoField(primary_key=True, serialize=False)),
                ('nama_grooming', models.CharField(max_length=100)),
                ('harga_grooming', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deskripsi_grooming', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Layanan Grooming',
                'db_table': 'layanan_grooming',
            },
        ),
        migrations.CreateModel(
            name='LayananKesehatan',
            fields=[
                ('id_kesehatan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kesehatan', models.CharField(max_length=100)),
                ('harga_kesehatan', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deskripsi', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Layanan Kesehatan',
                'db_table': 'layanan_kesehatan',
            },
        ),
        migrations.CreateModel(
            name='LayananPenitipan',
            fields=[
                ('id_penitipan', models.AutoField(primary_key=True, serialize=False)),
                ('jenis_penitipan', models.CharField(max_length=100)),
                ('harga_penitipan', models.DecimalField(decimal_places=2, max_digits=8)),
                ('kapasitas_penitipan', models.IntegerField()),
                ('deskripsi_penitipan', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Layanan Penitipan',
                'db_table': 'layanan_penitipan',
            },
        ),
    ]
