# Generated by Django 5.2.5 on 2025-08-11 14:03

import layanan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layanankesehatan',
            old_name='deskripsi',
            new_name='deskripsi_kesehatan',
        ),
        migrations.AddField(
            model_name='layanangrooming',
            name='foto_grooming',
            field=models.ImageField(blank=True, null=True, upload_to=layanan.models.layanan_image_upload_path),
        ),
        migrations.AddField(
            model_name='layanankesehatan',
            name='foto_kesehatan',
            field=models.ImageField(blank=True, null=True, upload_to=layanan.models.layanan_image_upload_path),
        ),
        migrations.AddField(
            model_name='layananpenitipan',
            name='foto_penitipan',
            field=models.ImageField(blank=True, null=True, upload_to=layanan.models.layanan_image_upload_path),
        ),
    ]
