"""
Django settings for bubusite project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%xt618%*5go6544jk7-va^=i@78sd9_=ku1xl3y&g9vifc#*r5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["bubupetshop.onrender.com",
                 "http://127.0.0.1:8000/",
                 ]


# Application definition

INSTALLED_APPS = [
   
    'jazzmin',
    'rangefilter',  
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'user',
    'peliharaan',
    'produk',
    'layanan',
    'bookinglayanan',
    'detailpetcare',
    'syaratdanketentuan',
    'riwayatpenjualan',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'bubusite.middleware.AlreadyLoggedInMiddleware',
    'bubusite.middleware.OnlyCustomersMiddleware',
]

ROOT_URLCONF = 'bubusite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'user.context_processors.detail_petcare',
                'user.context_processors.current_route',
            ],
        },
    },
]

WSGI_APPLICATION = 'bubusite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'id'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

AUTH_USER_MODEL = 'user.User'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JAZZMIN_SETTINGS = {
  "site_logo": "base-img/icon.png",
  "login_logo": "base-img/icon.png",
  "login_logo_dark": "base-img/icon.png",
  "site_logo_classes": "img-circle",
  "site_icon": "base-img/icon.png",
  "welcome_sign": "Welcome to the Bubu Petshop admin panel",
  "site_title": "Bubu Petshop Admin",
  "site_header": "Bubu Petshop Administration",
  "site_brand": "Bubu Petshop",
  "copyright": "Bubu Petshop",
  "show_ui_builder": True,
  "icons": {
    "auth.User": "fas fa-users",
    "auth.Group": "fas fa-users-cog",
    "user.User": "fas fa-user",
    "produk.Produk": "fas fa-box-open",
    "bookinglayanan.BookingLayanan": "fas fa-calendar-check",
    "peliharaan.Peliharaan": "fas fa-paw",
    "layanan.LayananPenitipan": "fas fa-hand-holding-heart",
    "layanan.LayananGrooming": "fas fa-scissors",
    "layanan.LayananKesehatan": "fas fa-notes-medical", 
    "detailpetcare.DetailPetCare": "fas fa-info-circle",
    "riwayatpenjualan.RiwayatPenjualan": "fas fa-history",
  },
  "show_sidebar": True,
  "navigation_expanded": True,
  "hide_apps": [],
  "hide_models": ["user.User"],
  "order_with_respect_to": [
    "bookinglayanan",
    "produk",
    "peliharaan",
    "layanan",
    "riwayatpenjualan",
    "auth",
    "user",
  ],
  
    "topmenu_links": [
      {"app": "layanan"},
      {"name": "Produk",  "url": "/admin/produk/produk/", "permissions": ["produk.view_produk"]},
      {"name": "Riwayat Penjualan", "url": "/admin/riwayatpenjualan/riwayatpenjualan/", "permissions": ["riwayatpenjualan.view_riwayatpenjualan"]},

    ],

  "custom_links": {
    "root": [{
        "name": "Dashboard B",
        "url": "/admin/",
        "icon": "fas fa-tachometer-alt",
        "permissions": ["auth.view_user"]
    }],
  
    "auth": [{
        "name": "Pengguna",
        "url": "/admin/user/user/",
        "icon": "fas fa-users",
        "permissions": ["user.view_user"]
    }],
  }
  

}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-orange",
    "accent": "accent-info",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-orange",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-warning",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-warning"
    }
}