# Generated by Django 5.2.5 on 2025-08-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id_produk', models.AutoField(primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=200)),
                ('harga_produk', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stok_produk', models.IntegerField()),
                ('kategori', models.CharField(choices=[('food', 'Makanan'), ('toy', 'Mainan'), ('accessory', 'Aksesoris'), ('medicine', 'Obat-obatan')], max_length=50)),
                ('deskripsi_produk', models.TextField(blank=True, null=True)),
                ('gambar_produk', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
