# Generated by Django 5.2.5 on 2025-08-07 11:40

import produk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='gambar_produk',
            field=models.ImageField(blank=True, null=True, upload_to=produk.models.produk_image_upload_path),
        ),
        migrations.AlterModelTable(
            name='produk',
            table='produk',
        ),
    ]
