# Generated by Django 5.2.5 on 2025-08-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_alter_produk_gambar_produk_alter_produk_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produk',
            options={'verbose_name_plural': 'Produk'},
        ),
    ]
