# Generated by Django 5.2.5 on 2025-08-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatPenjualan',
            fields=[
                ('id_penjualan', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_penjualan', models.DateTimeField(auto_now_add=True)),
                ('pelanggan', models.CharField(max_length=255)),
                ('layanan', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], max_length=20)),
                ('total_penjualan', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Riwayat Penjualan',
                'db_table': 'riwayat_penjualan',
            },
        ),
    ]
