# Generated by Django 5.2.5 on 2025-08-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPetcare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_petcare', models.CharField(max_length=50)),
                ('tlp_petcare', models.CharField(max_length=20)),
                ('email_petcare', models.CharField(max_length=100)),
                ('alamat_petcare', models.TextField()),
                ('maps_petcare', models.CharField(max_length=200)),
                ('deskripsi_petcare', models.TextField()),
                ('rekening_petcare', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Detail Petcare',
                'db_table': 'detail_petcare',
            },
        ),
    ]
