# Generated by Django 5.2.5 on 2025-08-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailpetcare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpetcare',
            name='maps_petcare',
            field=models.CharField(max_length=1000),
        ),
    ]
