# Generated by Django 5.2.5 on 2025-08-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailpetcare', '0002_alter_detailpetcare_maps_petcare'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpetcare',
            name='nama_bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detailpetcare',
            name='pemilik_rekening',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detailpetcare',
            name='alamat_petcare',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailpetcare',
            name='deskripsi_petcare',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailpetcare',
            name='maps_petcare',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='detailpetcare',
            name='rekening_petcare',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
