# Generated by Django 5.2.5 on 2025-08-07 13:14

import django.db.models.deletion
import peliharaan.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peliharaan',
            fields=[
                ('id_hewan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_hewan', models.CharField(max_length=50)),
                ('jenis_hewan', models.CharField(choices=[('cat', 'Kucing'), ('dog', 'Anjing'), ('other', 'lainya')], max_length=50)),
                ('umur_hewan', models.IntegerField()),
                ('berat_hewan', models.DecimalField(decimal_places=2, max_digits=5)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('foto_peliharaan', models.ImageField(blank=True, null=True, upload_to=peliharaan.models.peliharaan_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'peliharaan',
            },
        ),
    ]
