# Generated by Django 5.2.5 on 2025-08-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliharaan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peliharaan',
            options={'verbose_name_plural': 'Peliharaan'},
        ),
    ]
