# Generated by Django 5.2.5 on 2025-08-07 14:17

import bookinglayanan.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layanan', '0001_initial'),
        ('peliharaan', '0002_alter_peliharaan_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLayanan',
            fields=[
                ('id_booking', models.AutoField(primary_key=True, serialize=False)),
                ('tipe_layanan', models.CharField(choices=[('grooming', 'Grooming'), ('sitting', 'Penitipan'), ('medical', 'Kesehatan')], max_length=20)),
                ('harga_booking', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tanggal_booking', models.DateTimeField(auto_now_add=True)),
                ('tanggal_selesai', models.DateTimeField(blank=True, null=True)),
                ('durasi_layanan', models.IntegerField(blank=True, null=True)),
                ('status_booking', models.CharField(choices=[('pending', 'Menunggu'), ('confirmed', 'Dikonfirmasi'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20)),
                ('catatan_booking', models.TextField(blank=True, null=True)),
                ('bukti_pembayaran', models.ImageField(blank=True, null=True, upload_to=bookinglayanan.models.buktibayar_image_upload_path)),
                ('booking_grooming', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='layanan.layanangrooming')),
                ('booking_kesehatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='layanan.layanankesehatan')),
                ('booking_penitipan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='layanan.layananpenitipan')),
                ('id_hewan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliharaan.peliharaan')),
            ],
            options={
                'verbose_name_plural': 'Booking Layanan',
                'db_table': 'booking_layanan',
            },
        ),
    ]
