# Generated by Django 5.2.5 on 2025-08-17 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinglayanan', '0002_bookinglayanan_id_user_and_more'),
        ('layanan', '0002_rename_deskripsi_layanankesehatan_deskripsi_kesehatan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinglayanan',
            options={'verbose_name_plural': 'Daftar Booking'},
        ),
        migrations.CreateModel(
            name='DailyCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('kapasitas_tersedia', models.IntegerField()),
                ('layanan_penitipan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layanan.layananpenitipan')),
            ],
            options={
                'verbose_name_plural': 'Daily Capacities',
                'unique_together': {('layanan_penitipan', 'tanggal')},
            },
        ),
    ]
