# Generated by Django 5.2.5 on 2025-08-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinglayanan', '0003_alter_bookinglayanan_options_dailycapacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayananHarianConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_layanan', models.CharField(help_text='Harus sama persis dengan nama di form booking', max_length=100, unique=True)),
                ('max_booking_per_hari', models.PositiveIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Konfigurasi Layanan Harian',
                'verbose_name_plural': 'Konfigurasi Layanan Harian',
            },
        ),
    ]
