# Generated by Django 5.2.5 on 2025-08-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinglayanan', '0004_layananharianconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='KuotaHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_layanan', models.CharField(choices=[('grooming', 'Grooming'), ('sitting', 'Penitipan'), ('medical', 'Kesehatan')], help_text='Pilih tipe layanan (misal: grooming)', max_length=20, unique=True)),
                ('max_booking_per_hari', models.PositiveIntegerField(default=10, verbose_name='Kuota Maksimal per Hari')),
            ],
            options={
                'verbose_name': 'Pengaturan Kuota Harian',
                'verbose_name_plural': 'Pengaturan Kuota Harian',
            },
        ),
        migrations.DeleteModel(
            name='LayananHarianConfig',
        ),
    ]
