# Generated by Django 5.2.5 on 2025-08-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookinglayanan', '0005_kuotaharian_delete_layananharianconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KuotaHarian',
        ),
    ]
