# Generated by Django 5.2.5 on 2025-08-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_terakhir_login_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
