# Generated by Django 5.2.5 on 2025-08-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_alamat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no_hp',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
